import { ThemeProvider } from "@emotion/react";
import {
  Box,
  Button,
  Card,
  CardActions,
  CardContent,
  Container,
  Typography,
  useTheme,
} from "@mui/material";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { getTheme } from "~/styles/theme";
import { api } from "~/utils/api";

export default function Home() {
  const theme = useTheme();
  return (
    <>
      <Head>
        <title>Hotel Booking - Book Your Next Destination Today!</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <ThemeProvider theme={getTheme("dark")}>
        <Box className="relative h-[26rem] w-full">
          <Container
            maxWidth="md"
            className="absolute bottom-0 left-0 right-0 z-20"
          >
            <Typography
              component="h1"
              variant="h3"
              color="text.primary"
              className="mb-2 drop-shadow"
            >
              Hassle-free hotel
              <br />
              booking in seconds.
            </Typography>
            <Typography
              component="p"
              variant="h5"
              color="text.secondary"
              className="mb-16 drop-shadow"
            >
              Find your perfect stay from over 50,000 hotels in 80 destinations
              <br />
              around the world.
            </Typography>
          </Container>
          <Image
            src="/img/home/boardwalk.JPG"
            fill={true}
            alt="Hero Image of Santa Cruz Boardwalk"
            className="object-cover brightness-150"
          />
          <div className="absolute z-10 h-full w-full bg-gradient-to-b from-transparent via-[rgba(0,0,0,0.3)] to-black"></div>
          <ThemeProvider theme={theme}>
            <Container
              maxWidth="md"
              className="absolute -bottom-6 left-0 right-0 z-20"
            >
              <Card className="h-12 w-full">
                <CardContent></CardContent>
              </Card>
            </Container>
          </ThemeProvider>
        </Box>
      </ThemeProvider>
    </>
  );
}
