import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hotel Booking - Book Your Next Destination Today!</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div className="bg-background h-24 w-24">This is the home page.</div>
    </>
  );
}
